if(EXISTS "/home/warrior/project/miniob/unittest/arithmetic_expression_test[1]_tests.cmake")
  include("/home/warrior/project/miniob/unittest/arithmetic_expression_test[1]_tests.cmake")
else()
  add_test(arithmetic_expression_test_NOT_BUILT arithmetic_expression_test_NOT_BUILT)
endif()
